version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    entrypoint: /entrypoint.sh
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "80"
