# Generated by Django 3.0.7 on 2020-08-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200805_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
